Repository wafflestudio/csereal-server, pull requests merged in 2023-09, with the labels that each got.

#53 [Refactor] 로그인, file uri 배포 환경에 맞게 수정
  src/main/kotlin/com/wafflestudio/csereal/common/config/SecurityConfig.kt
  src/main/kotlin/com/wafflestudio/csereal/core/resource/mainImage/api/FileController.kt
  src/main/resources/application.yaml
Labels: Refactor, Feat: API

#56 fix: https 관련 로그인 수정
  caddy/Caddyfile
  src/main/kotlin/com/wafflestudio/csereal/common/config/SecurityConfig.kt
Labels: Fix

#59 feat: 신임교수초빙
  src/main/kotlin/com/wafflestudio/csereal/core/recruit/api/RecruitController.kt
  src/main/kotlin/com/wafflestudio/csereal/core/recruit/database/RecruitEntity.kt
  src/main/kotlin/com/wafflestudio/csereal/core/recruit/database/RecruitRepository.kt
  src/main/kotlin/com/wafflestudio/csereal/core/recruit/dto/RecruitPage.kt
  src/main/kotlin/com/wafflestudio/csereal/core/recruit/service/RecruitService.kt
Labels: Feat: API

#60 feat: 행정실 권한 체크 API
  src/main/kotlin/com/wafflestudio/csereal/core/user/api/UserController.kt
  src/main/kotlin/com/wafflestudio/csereal/core/user/dto/StaffAuthResponse.kt
  src/main/kotlin/com/wafflestudio/csereal/core/user/service/UserService.kt
Labels: Feat: API

#55 [CICD] mainImage, attachment 경로 mount 설정
  Dockerfile
  docker-compose-backend.yml
Labels: CICD

#58 [Feat] 예전 url과 비슷하게 이전 파일(사진)들 접근할 수 있도록 controller 생성
  Dockerfile
  caddy/Caddyfile
  docker-compose-backend.yml
  src/main/kotlin/com/wafflestudio/csereal/core/resource/mainImage/api/DeprecatedFileController.kt
  src/main/resources/application.yaml
Labels: Feat: API, CICD

#62 [Hotfix] Deploy 환경 변수 누락, 최신 docker image pull하도록 수정.
  .github/workflows/deploy.yaml
  docker-compose-backend.yml
Labels: Hotfix, CICD

#63 [Hotfix]: Old File Serving
  src/main/kotlin/com/wafflestudio/csereal/core/resource/mainImage/api/DeprecatedFileController.kt
Labels: Hotfix, Feat: API

#61 fix: 예약 dto에 지도교수, 반복 횟수 추가
  src/main/kotlin/com/wafflestudio/csereal/core/reservation/database/ReservationEntity.kt
  src/main/kotlin/com/wafflestudio/csereal/core/reservation/dto/ReservationDto.kt
  src/main/kotlin/com/wafflestudio/csereal/core/reservation/dto/ReserveRequest.kt
  src/main/kotlin/com/wafflestudio/csereal/core/reservation/service/ReservationService.kt
Labels: Fix

#64 fix: 로그아웃 엔드포인트 변경
  src/main/kotlin/com/wafflestudio/csereal/common/config/SecurityConfig.kt
Labels: Fix

#65 [Fix] Notice, News Description TEXT type으로 변환
  src/main/kotlin/com/wafflestudio/csereal/core/news/database/NewsEntity.kt
  src/main/kotlin/com/wafflestudio/csereal/core/notice/database/NoticeEntity.kt
  src/main/kotlin/com/wafflestudio/csereal/core/seminar/database/SeminarEntity.kt
Labels: Fix, Feat: DB

#68 fix: 파일 업로드 경로 통일
  src/main/kotlin/com/wafflestudio/csereal/core/notice/dto/NoticeDto.kt
  src/main/kotlin/com/wafflestudio/csereal/core/resource/attachment/service/AttachmentService.kt
  src/main/kotlin/com/wafflestudio/csereal/core/resource/mainImage/api/FileController.kt
  src/main/kotlin/com/wafflestudio/csereal/core/resource/mainImage/service/MainImageService.kt
  src/main/resources/application.yaml
Labels: Fix

#70 fix: total 쿼리 최적화
  src/main/kotlin/com/wafflestudio/csereal/core/news/database/NewsRepository.kt
  src/main/kotlin/com/wafflestudio/csereal/core/news/dto/NewsSearchResponse.kt
  src/main/kotlin/com/wafflestudio/csereal/core/notice/database/NoticeRepository.kt
  src/main/kotlin/com/wafflestudio/csereal/core/notice/dto/NoticeSearchResponse.kt
  src/main/kotlin/com/wafflestudio/csereal/core/seminar/database/SeminarRepository.kt
  src/main/kotlin/com/wafflestudio/csereal/core/seminar/dto/SeminarSearchResponse.kt
Labels: Fix

#71 Fix: additional note column type to text
  src/main/kotlin/com/wafflestudio/csereal/core/seminar/database/SeminarEntity.kt
Labels: Fix, Feat: DB

#75 fix: 이전 글 다음 글만 fetch 하도록 쿼리 최적화
  src/main/kotlin/com/wafflestudio/csereal/core/notice/api/NoticeController.kt
  src/main/kotlin/com/wafflestudio/csereal/core/notice/database/NoticeRepository.kt
  src/main/kotlin/com/wafflestudio/csereal/core/notice/dto/NoticeDto.kt
  src/main/kotlin/com/wafflestudio/csereal/core/notice/service/NoticeService.kt
Labels: Fix

#77 CI/CD: Test 설정
  .github/workflows/build_and_test.yaml
  build.gradle.kts
  src/main/resources/application.yaml
  src/test/kotlin/com/wafflestudio/csereal/global/config/TestConfig.kt
Labels: CICD

#79 [Feat] Seminar plain text field 추가
  src/main/kotlin/com/wafflestudio/csereal/core/seminar/database/SeminarEntity.kt
  src/main/kotlin/com/wafflestudio/csereal/core/seminar/database/SeminarRepository.kt
  src/test/kotlin/com/wafflestudio/csereal/core/seminar/service/SeminarServiceTest.kt
Labels: Feat: DB

#80 Feat: News plain text field 추가
  src/main/kotlin/com/wafflestudio/csereal/core/news/database/NewsEntity.kt
  src/main/kotlin/com/wafflestudio/csereal/core/news/database/NewsRepository.kt
  src/test/kotlin/com/wafflestudio/csereal/core/notice/news/NewsServiceTest.kt
Labels: Feat: DB

#81 Feat: 구성원 검색 위한 table 추가.
  src/main/kotlin/com/wafflestudio/csereal/core/member/database/MemberSearchEntity.kt
  src/main/kotlin/com/wafflestudio/csereal/core/member/database/MemberSearchRepository.kt
  src/main/kotlin/com/wafflestudio/csereal/core/member/database/ProfessorEntity.kt
  src/main/kotlin/com/wafflestudio/csereal/core/member/database/StaffEntity.kt
  src/main/kotlin/com/wafflestudio/csereal/core/member/service/MemberSearchService.kt
  src/main/kotlin/com/wafflestudio/csereal/core/member/service/ProfessorService.kt
  src/main/kotlin/com/wafflestudio/csereal/core/member/service/StaffService.kt
  src/test/kotlin/com/wafflestudio/csereal/core/member/service/ProfessorServiceTest.kt
  src/test/kotlin/com/wafflestudio/csereal/core/member/service/StaffServiceTest.kt
Labels: Feat: Logic, Feat: DB

#82 fix: 새소식 세미나 쿼리 수정
  build.gradle.kts
  src/main/kotlin/com/wafflestudio/csereal/common/utils/FixedPageRequest.kt
  src/main/kotlin/com/wafflestudio/csereal/common/utils/Utils.kt
  src/main/kotlin/com/wafflestudio/csereal/core/news/api/NewsController.kt
  src/main/kotlin/com/wafflestudio/csereal/core/news/database/NewsEntity.kt
  src/main/kotlin/com/wafflestudio/csereal/core/news/database/NewsRepository.kt
  src/main/kotlin/com/wafflestudio/csereal/core/news/dto/NewsDto.kt
  src/main/kotlin/com/wafflestudio/csereal/core/news/service/NewsService.kt
  src/main/kotlin/com/wafflestudio/csereal/core/notice/api/NoticeController.kt
  src/main/kotlin/com/wafflestudio/csereal/core/notice/database/NoticeEntity.kt
  src/main/kotlin/com/wafflestudio/csereal/core/notice/database/NoticeRepository.kt
  src/main/kotlin/com/wafflestudio/csereal/core/notice/service/NoticeService.kt
  src/main/kotlin/com/wafflestudio/csereal/core/seminar/api/SeminarController.kt
  src/main/kotlin/com/wafflestudio/csereal/core/seminar/database/SeminarEntity.kt
  src/main/kotlin/com/wafflestudio/csereal/core/seminar/database/SeminarRepository.kt
  src/main/kotlin/com/wafflestudio/csereal/core/seminar/dto/SeminarDto.kt
  src/main/kotlin/com/wafflestudio/csereal/core/seminar/service/SeminarService.kt
  src/main/resources/application.yaml
Labels: Fix, Refactor

#85 Feat: 구성원 검색 API 추가
  .github/workflows/database.yaml
  db_config/config.cnf
  docker-compose-db.yml
  docker-compose-local.yml
  src/main/kotlin/com/wafflestudio/csereal/common/config/MySQLDialectCustom.kt
  src/main/kotlin/com/wafflestudio/csereal/core/member/api/MemberSearchController.kt
  src/main/kotlin/com/wafflestudio/csereal/core/member/database/MemberSearchRepository.kt
  src/main/kotlin/com/wafflestudio/csereal/core/member/dto/MemberSearchPageResponse.kt
  src/main/kotlin/com/wafflestudio/csereal/core/member/dto/MemberSearchResponseElement.kt
  src/main/kotlin/com/wafflestudio/csereal/core/member/dto/MemberSearchTopResponse.kt
  src/main/kotlin/com/wafflestudio/csereal/core/member/service/MemberSearchService.kt
  src/main/resources/application.yaml
Labels: Feat: API, Feat: Logic, Feat: DB, CICD

#97 Feat: 연구 탭 통합검색 위한 Table 생성.
  src/main/kotlin/com/wafflestudio/csereal/core/conference/database/ConferenceEntity.kt
  src/main/kotlin/com/wafflestudio/csereal/core/member/service/MemberSearchService.kt
  src/main/kotlin/com/wafflestudio/csereal/core/research/database/LabEntity.kt
  src/main/kotlin/com/wafflestudio/csereal/core/research/database/ResearchEntity.kt
  src/main/kotlin/com/wafflestudio/csereal/core/research/database/ResearchPostType.kt
  src/main/kotlin/com/wafflestudio/csereal/core/research/database/ResearchSearchEntity.kt
  src/main/kotlin/com/wafflestudio/csereal/core/research/database/ResearchSearchRepository.kt
  src/main/kotlin/com/wafflestudio/csereal/core/research/service/ResearchSearchService.kt
  src/main/kotlin/com/wafflestudio/csereal/core/research/service/ResearchService.kt
Labels: Feat: Logic, Feat: DB

#98 Feat: Lab Update API 추가
  src/main/kotlin/com/wafflestudio/csereal/core/conference/database/ConferenceEntity.kt
  src/main/kotlin/com/wafflestudio/csereal/core/research/api/ResearchController.kt
  src/main/kotlin/com/wafflestudio/csereal/core/research/database/LabEntity.kt
  src/main/kotlin/com/wafflestudio/csereal/core/research/dto/LabUpdateRequest.kt
  src/main/kotlin/com/wafflestudio/csereal/core/research/service/ResearchService.kt
  src/main/kotlin/com/wafflestudio/csereal/core/resource/attachment/service/AttachmentService.kt
  src/test/kotlin/com/wafflestudio/csereal/core/reseach/service/ResearchServiceTest.kt
Labels: Feat: API, Feat: Logic

#99 Feat: Conference page 수정 API
  src/main/kotlin/com/wafflestudio/csereal/core/conference/api/ConferenceController.kt
  src/main/kotlin/com/wafflestudio/csereal/core/conference/database/ConferenceEntity.kt
  src/main/kotlin/com/wafflestudio/csereal/core/conference/database/ConferencePageEntity.kt
  src/main/kotlin/com/wafflestudio/csereal/core/conference/database/ConferenceRepository.kt
  src/main/kotlin/com/wafflestudio/csereal/core/conference/dto/ConferenceCreateDto.kt
  src/main/kotlin/com/wafflestudio/csereal/core/conference/dto/ConferenceDto.kt
  src/main/kotlin/com/wafflestudio/csereal/core/conference/dto/ConferenceModifyRequest.kt
  src/main/kotlin/com/wafflestudio/csereal/core/conference/dto/ConferencePage.kt
  src/main/kotlin/com/wafflestudio/csereal/core/conference/service/ConferenceService.kt
  src/test/kotlin/com/wafflestudio/csereal/core/conference/service/ConferenceServiceTest.kt
Labels: Feat: API, Feat: Logic

#102 Refactor: Extract Full Text Query Template to CommonRepository
  src/main/kotlin/com/wafflestudio/csereal/common/config/MySQLDialectCustom.kt
  src/main/kotlin/com/wafflestudio/csereal/common/repository/CommonRepository.kt
  src/main/kotlin/com/wafflestudio/csereal/core/member/database/MemberSearchRepository.kt
Labels: Refactor

#84 feat: API 권한 체크
  src/main/kotlin/com/wafflestudio/csereal/core/about/api/AboutController.kt
  src/main/kotlin/com/wafflestudio/csereal/core/academics/api/AcademicsController.kt
  src/main/kotlin/com/wafflestudio/csereal/core/admin/api/AdminController.kt
  src/main/kotlin/com/wafflestudio/csereal/core/admissions/api/AdmissionsController.kt
  src/main/kotlin/com/wafflestudio/csereal/core/member/api/ProfessorController.kt
  src/main/kotlin/com/wafflestudio/csereal/core/member/api/StaffController.kt
  src/main/kotlin/com/wafflestudio/csereal/core/news/api/NewsController.kt
  src/main/kotlin/com/wafflestudio/csereal/core/notice/api/NoticeController.kt
  src/main/kotlin/com/wafflestudio/csereal/core/research/api/ResearchController.kt
  src/main/kotlin/com/wafflestudio/csereal/core/resource/mainImage/api/FileController.kt
  src/main/kotlin/com/wafflestudio/csereal/core/seminar/api/SeminarController.kt
Labels: Feat: API

#113 refactor: 공지 태그 응답 한국어로 변경 및 리팩토링
  src/main/kotlin/com/wafflestudio/csereal/core/news/database/NewsRepository.kt
  src/main/kotlin/com/wafflestudio/csereal/core/news/database/TagInNewsEnum.kt
  src/main/kotlin/com/wafflestudio/csereal/core/news/dto/NewsDto.kt
  src/main/kotlin/com/wafflestudio/csereal/core/notice/database/TagInNoticeEnum.kt
  src/main/kotlin/com/wafflestudio/csereal/core/notice/dto/NoticeDto.kt
Labels: Fix, Refactor

#114 fix: 공지 새소식 PATCH 로직 수정
  src/main/kotlin/com/wafflestudio/csereal/core/news/api/NewsController.kt
  src/main/kotlin/com/wafflestudio/csereal/core/news/service/NewsService.kt
  src/main/kotlin/com/wafflestudio/csereal/core/notice/api/NoticeController.kt
  src/main/kotlin/com/wafflestudio/csereal/core/notice/service/NoticeService.kt
  src/test/kotlin/com/wafflestudio/csereal/core/notice/news/NewsServiceTest.kt
  src/test/kotlin/com/wafflestudio/csereal/core/notice/service/NoticeServiceTest.kt
Labels: Fix, Refactor

#116 Feat: 검색 결과에서 keyword 위치, 적절한 substring 추출 위한 method 추가
  src/main/kotlin/com/wafflestudio/csereal/common/utils/Utils.kt
  src/test/kotlin/com/wafflestudio/csereal/common/util/UtilsTest.kt
Labels: Feat: Logic

#117 fix: total 더미 값 + pageNum null일때만 더미 값 주기
  src/main/kotlin/com/wafflestudio/csereal/core/news/api/NewsController.kt
  src/main/kotlin/com/wafflestudio/csereal/core/news/database/NewsRepository.kt
  src/main/kotlin/com/wafflestudio/csereal/core/notice/api/NoticeController.kt
  src/main/kotlin/com/wafflestudio/csereal/core/notice/database/NoticeRepository.kt
  src/main/kotlin/com/wafflestudio/csereal/core/seminar/api/SeminarController.kt
  src/main/kotlin/com/wafflestudio/csereal/core/seminar/database/SeminarRepository.kt
Labels: Fix

#119 fix: 예약 조회 권한 분리 및 응답 단순화
  src/main/kotlin/com/wafflestudio/csereal/core/conference/service/ConferenceService.kt
  src/main/kotlin/com/wafflestudio/csereal/core/notice/service/NoticeService.kt
  src/main/kotlin/com/wafflestudio/csereal/core/reservation/api/ReservceController.kt
  src/main/kotlin/com/wafflestudio/csereal/core/reservation/dto/ReservationDto.kt
  src/main/kotlin/com/wafflestudio/csereal/core/reservation/dto/SimpleReservationDto.kt
  src/main/kotlin/com/wafflestudio/csereal/core/reservation/service/ReservationService.kt
Labels: Fix

#121 fix: 로그인 리다이렉트 엔드포인트
  src/main/kotlin/com/wafflestudio/csereal/common/config/CustomAuthenticationSuccessHandler.kt
  src/main/kotlin/com/wafflestudio/csereal/common/config/SecurityConfig.kt
Labels: Fix

#126 feat: LocalDateTime 응답 마지막에 Z 추가
  src/main/kotlin/com/wafflestudio/csereal/common/config/JacksonConfig.kt
Labels: Feat: Logic

#127 refactor: deleteIds request 내부로 이동
  src/main/kotlin/com/wafflestudio/csereal/core/news/api/NewsController.kt
  src/main/kotlin/com/wafflestudio/csereal/core/news/dto/NewsDto.kt
  src/main/kotlin/com/wafflestudio/csereal/core/news/service/NewsService.kt
  src/main/kotlin/com/wafflestudio/csereal/core/notice/api/NoticeController.kt
  src/main/kotlin/com/wafflestudio/csereal/core/notice/dto/NoticeDto.kt
  src/main/kotlin/com/wafflestudio/csereal/core/notice/service/NoticeService.kt
  src/main/kotlin/com/wafflestudio/csereal/core/resource/attachment/service/AttachmentService.kt
  src/main/kotlin/com/wafflestudio/csereal/core/seminar/api/SeminarController.kt
  src/main/kotlin/com/wafflestudio/csereal/core/seminar/dto/SeminarDto.kt
  src/main/kotlin/com/wafflestudio/csereal/core/seminar/service/SeminarService.kt
  src/test/kotlin/com/wafflestudio/csereal/core/notice/news/NewsServiceTest.kt
  src/test/kotlin/com/wafflestudio/csereal/core/notice/service/NoticeServiceTest.kt
  src/test/kotlin/com/wafflestudio/csereal/core/seminar/service/SeminarServiceTest.kt
Labels: Refactor

#128 fix: 확장자 중복 버그
  src/main/kotlin/com/wafflestudio/csereal/core/resource/attachment/service/AttachmentService.kt
Labels: Bug, Fix

#129 feat: 관리자는 새소식, 세미나 목록에서 비공개 글 확인 가능
  src/main/kotlin/com/wafflestudio/csereal/core/news/api/NewsController.kt
  src/main/kotlin/com/wafflestudio/csereal/core/news/database/NewsRepository.kt
  src/main/kotlin/com/wafflestudio/csereal/core/news/dto/NewsSearchDto.kt
  src/main/kotlin/com/wafflestudio/csereal/core/news/service/NewsService.kt
  src/main/kotlin/com/wafflestudio/csereal/core/seminar/api/SeminarController.kt
  src/main/kotlin/com/wafflestudio/csereal/core/seminar/database/SeminarRepository.kt
  src/main/kotlin/com/wafflestudio/csereal/core/seminar/dto/SeminarSearchDto.kt
  src/main/kotlin/com/wafflestudio/csereal/core/seminar/service/SeminarService.kt
Labels: Feat: API

#122 Fix: 키워드 추출 함수 수정
  src/main/kotlin/com/wafflestudio/csereal/common/utils/Utils.kt
  src/test/kotlin/com/wafflestudio/csereal/common/util/UtilsTest.kt
Labels: Bug, Fix

#123 Feat: 통합검색 Notice API 구현
  src/main/kotlin/com/wafflestudio/csereal/core/notice/api/NoticeController.kt
  src/main/kotlin/com/wafflestudio/csereal/core/notice/database/NoticeRepository.kt
  src/main/kotlin/com/wafflestudio/csereal/core/notice/dto/NoticeTotalSearchElement.kt
  src/main/kotlin/com/wafflestudio/csereal/core/notice/dto/NoticeTotalSearchResponse.kt
  src/main/kotlin/com/wafflestudio/csereal/core/notice/service/NoticeService.kt
Labels: Feat: API, Feat: Logic

#124 Feat: News 통합 검색 API 구현
  src/main/kotlin/com/wafflestudio/csereal/core/news/api/NewsController.kt
  src/main/kotlin/com/wafflestudio/csereal/core/news/database/NewsRepository.kt
  src/main/kotlin/com/wafflestudio/csereal/core/news/dto/NewsTotalSearchDto.kt
  src/main/kotlin/com/wafflestudio/csereal/core/news/dto/NewsTotalSearchElement.kt
  src/main/kotlin/com/wafflestudio/csereal/core/news/service/NewsService.kt
Labels: Feat: API, Feat: Logic

#133 feat: 파일 업로드 api
  src/main/kotlin/com/wafflestudio/csereal/core/resource/attachment/api/AttachmentController.kt
  src/main/kotlin/com/wafflestudio/csereal/core/resource/attachment/service/AttachmentService.kt
  src/main/kotlin/com/wafflestudio/csereal/core/resource/common/api/DeprecatedFileController.kt
  src/main/kotlin/com/wafflestudio/csereal/core/resource/common/api/FileController.kt
  src/main/kotlin/com/wafflestudio/csereal/core/resource/common/dto/FileUploadResponse.kt
  src/main/kotlin/com/wafflestudio/csereal/core/resource/mainImage/api/MainImageController.kt
  src/main/resources/application.yaml
Labels: Refactor, Feat: API

#134 Feat: Change titleForMain column to TEXT type.
  src/main/kotlin/com/wafflestudio/csereal/core/news/database/NewsEntity.kt
  src/main/kotlin/com/wafflestudio/csereal/core/notice/database/NoticeEntity.kt
  src/main/kotlin/com/wafflestudio/csereal/core/seminar/database/SeminarEntity.kt
Labels: Feat: DB

#138 Hotfix: Fix search total notice stringLength default value.
  src/main/kotlin/com/wafflestudio/csereal/core/notice/api/NoticeController.kt
Labels: Hotfix, Feat: API

#142 Hotfix: Fix main page orderby exception.
  src/main/kotlin/com/wafflestudio/csereal/core/main/database/MainRepository.kt
  src/main/kotlin/com/wafflestudio/csereal/core/main/dto/MainNoticeResponse.kt
Labels: Hotfix

#144 Feat: 뉴스 날짜로 정렬
  src/main/kotlin/com/wafflestudio/csereal/core/news/database/NewsEntity.kt
  src/main/kotlin/com/wafflestudio/csereal/core/news/database/NewsRepository.kt
  src/main/kotlin/com/wafflestudio/csereal/core/news/dto/NewsDto.kt
  src/test/kotlin/com/wafflestudio/csereal/core/news/NewsServiceTest.kt
Labels: Feat: Logic, Feat: DB

#146 Feat: Add description for slide.
  src/main/kotlin/com/wafflestudio/csereal/core/main/database/MainRepository.kt
  src/main/kotlin/com/wafflestudio/csereal/core/main/dto/MainSlideResponse.kt
Labels: Feat: API

#149 fix: 중요 안내
  src/main/kotlin/com/wafflestudio/csereal/core/admin/service/AdminService.kt
  src/main/kotlin/com/wafflestudio/csereal/core/main/database/MainRepository.kt
  src/main/kotlin/com/wafflestudio/csereal/core/news/database/NewsRepository.kt
  src/main/kotlin/com/wafflestudio/csereal/core/notice/database/NoticeRepository.kt
  src/main/kotlin/com/wafflestudio/csereal/core/seminar/database/SeminarRepository.kt
Labels: Fix

#154 fix: 첨부파일 다운로드
  src/main/kotlin/com/wafflestudio/csereal/core/resource/common/api/DeprecatedFileController.kt
  src/main/kotlin/com/wafflestudio/csereal/core/resource/common/api/FileController.kt
Labels: Fix

#153 Feat: 관리자 슬라이드에 total 추가, refactoring
  src/main/kotlin/com/wafflestudio/csereal/core/admin/api/AdminController.kt
  src/main/kotlin/com/wafflestudio/csereal/core/admin/database/AdminRepository.kt
  src/main/kotlin/com/wafflestudio/csereal/core/admin/dto/AdminSlideElement.kt
  src/main/kotlin/com/wafflestudio/csereal/core/admin/dto/AdminSlidesResponse.kt
  src/main/kotlin/com/wafflestudio/csereal/core/admin/service/AdminService.kt
  src/main/kotlin/com/wafflestudio/csereal/core/news/database/NewsRepository.kt
  src/main/kotlin/com/wafflestudio/csereal/core/news/service/NewsService.kt
  src/test/kotlin/com/wafflestudio/csereal/core/news/NewsServiceTest.kt
Labels: Refactor, Feat: API, Feat: Logic

#155 fix: 세미나 isYearLast 로직 수정
  src/main/kotlin/com/wafflestudio/csereal/core/seminar/database/SeminarRepository.kt
Labels: Fix

#158 fix: 메인 공지 정렬
  src/main/kotlin/com/wafflestudio/csereal/core/main/database/MainRepository.kt
Labels: Fix

#157 fix: 예약 조회 권한 수정
  src/main/kotlin/com/wafflestudio/csereal/core/reservation/api/ReservationController.kt
  src/main/kotlin/com/wafflestudio/csereal/core/reservation/database/ReservationEntity.kt
  src/main/kotlin/com/wafflestudio/csereal/core/reservation/dto/ReservationDto.kt
  src/main/kotlin/com/wafflestudio/csereal/core/reservation/service/ReservationService.kt
Labels: Fix

#156 Feat: 통합검색 정렬 최신순
  src/main/kotlin/com/wafflestudio/csereal/core/news/database/NewsRepository.kt
  src/main/kotlin/com/wafflestudio/csereal/core/notice/database/NoticeRepository.kt
Labels: Feat: Logic

#159 Feat: Admin Important에 pagination 추가, total 추가.
  src/main/kotlin/com/wafflestudio/csereal/core/admin/api/AdminController.kt
  src/main/kotlin/com/wafflestudio/csereal/core/admin/database/AdminRepository.kt
  src/main/kotlin/com/wafflestudio/csereal/core/admin/dto/AdminImportantElement.kt
  src/main/kotlin/com/wafflestudio/csereal/core/admin/dto/AdminImportantResponse.kt
  src/main/kotlin/com/wafflestudio/csereal/core/admin/service/AdminService.kt
Labels: Feat: API, Feat: Logic

#166 CICD: Add blocking backend api except frontend.
  .github/workflows/proxy.yaml
  caddy/Caddyfile
  docker-compose-caddy.yml
Labels: CICD

#167 fix: group 변경 반영
  src/main/kotlin/com/wafflestudio/csereal/core/user/database/UserEntity.kt
  src/main/kotlin/com/wafflestudio/csereal/core/user/service/CustomOidcUserService.kt
Labels: Fix, Feat: Logic

#168 refactor: 실제 스누씨 서버 연동
  .github/workflows/deploy.yaml
  docker-compose-backend.yml
  src/main/kotlin/com/wafflestudio/csereal/common/config/SecurityConfig.kt
  src/main/kotlin/com/wafflestudio/csereal/common/config/WebConfig.kt
  src/main/resources/application.yaml
Labels: Fix, Refactor
