Repository wafflestudio/csereal-server, pull requests merged in 2024-04, with the labels that each got.

#232 feat: 행정직원 정렬 순서 변경
  src/main/kotlin/com/wafflestudio/csereal/core/member/service/StaffService.kt
Labels: Feat: API, Feat: Logic

#235 feat: 한글 이름 우선순위 정렬
  src/main/kotlin/com/wafflestudio/csereal/common/utils/Utils.kt
  src/main/kotlin/com/wafflestudio/csereal/core/member/service/ProfessorService.kt
Labels: Feat: API, Feat: Logic

#236 Feat: 게시물 제외 통합검색에 사용되는 field들 refersh하는 API 추가
  src/main/kotlin/com/wafflestudio/csereal/core/about/service/AboutService.kt
  src/main/kotlin/com/wafflestudio/csereal/core/academics/service/AcademicsSearchService.kt
  src/main/kotlin/com/wafflestudio/csereal/core/admissions/service/AdmissionsService.kt
  src/main/kotlin/com/wafflestudio/csereal/core/main/api/MainController.kt
  src/main/kotlin/com/wafflestudio/csereal/core/main/event/RefreshSearchEvent.kt
  src/main/kotlin/com/wafflestudio/csereal/core/main/service/MainService.kt
  src/main/kotlin/com/wafflestudio/csereal/core/member/service/MemberSearchService.kt
  src/main/kotlin/com/wafflestudio/csereal/core/member/service/ProfessorService.kt
  src/main/kotlin/com/wafflestudio/csereal/core/research/service/ResearchSearchService.kt
Labels: Feat: API, Feat: Logic

#239 Fix: About Entity 누락된 "mappedBy" 값 추가
  src/main/kotlin/com/wafflestudio/csereal/core/about/database/AboutEntity.kt
Labels: Fix, Feat: DB

#241 fix: course 띄어쓰기 그대로 유지
  src/main/kotlin/com/wafflestudio/csereal/core/academics/database/CourseEntity.kt
Labels: Fix

#245 fix: stat year 2050년까지 확장
  src/main/kotlin/com/wafflestudio/csereal/core/about/database/StatRepository.kt
  src/main/kotlin/com/wafflestudio/csereal/core/about/service/AboutService.kt
Labels: Fix

#246 fix: adjust max thread and pool size
  src/main/resources/application.yaml
Labels: Fix

#247 Feat: 공지, 새소식, 세미나 정렬 옵션 추가
  src/main/kotlin/com/wafflestudio/csereal/common/enums/ContentSearchSortType.kt
  src/main/kotlin/com/wafflestudio/csereal/core/news/api/NewsController.kt
  src/main/kotlin/com/wafflestudio/csereal/core/news/database/NewsRepository.kt
  src/main/kotlin/com/wafflestudio/csereal/core/news/service/NewsService.kt
  src/main/kotlin/com/wafflestudio/csereal/core/notice/api/NoticeController.kt
  src/main/kotlin/com/wafflestudio/csereal/core/notice/database/NoticeRepository.kt
  src/main/kotlin/com/wafflestudio/csereal/core/notice/dto/NoticeSearchDto.kt
  src/main/kotlin/com/wafflestudio/csereal/core/notice/service/NoticeService.kt
  src/main/kotlin/com/wafflestudio/csereal/core/seminar/api/SeminarController.kt
  src/main/kotlin/com/wafflestudio/csereal/core/seminar/database/SeminarRepository.kt
  src/main/kotlin/com/wafflestudio/csereal/core/seminar/service/SeminarService.kt
Labels: Feat: API, Feat: Logic

#248 CICD: env 파일 분리, 서버 docker image tag 분리
  .github/workflows/database.yaml
  .github/workflows/database_dev.yaml
  .github/workflows/deploy.yaml
  .github/workflows/deploy_dev.yaml
  .github/workflows/proxy.yaml
  .github/workflows/proxy_dev.yaml
  docker-compose-backend.yml
Labels: CICD

#250 feat: 개인정보 동의 여부 기록
  src/main/kotlin/com/wafflestudio/csereal/core/reservation/database/ReservationEntity.kt
  src/main/kotlin/com/wafflestudio/csereal/core/reservation/dto/ReserveRequest.kt
  src/main/kotlin/com/wafflestudio/csereal/core/reservation/service/ReservationService.kt
Labels: Feat: API, Feat: Logic, Feat: DB

#252 Hotfix: Add env file dir for docker compose files
  docker-compose-backend.yml
  docker-compose-caddy.yml
  docker-compose-db.yml
Labels: Hotfix, CICD

#253 Hotfix: 경로 분리로 배포 문제 해결
  .github/workflows/database.yaml
  .github/workflows/database_dev.yaml
  .github/workflows/deploy.yaml
  .github/workflows/deploy_dev.yaml
  .github/workflows/proxy.yaml
  .github/workflows/proxy_dev.yaml
Labels: CICD

#254 Fix: notice keyword가 없을 시 오류 발생 수정
  src/main/kotlin/com/wafflestudio/csereal/core/notice/database/NoticeRepository.kt
  src/main/kotlin/com/wafflestudio/csereal/core/notice/dto/NoticeSearchDto.kt
Labels: Fix, Feat: Logic

#262 Config: Disable migrate on profile prod.
  src/main/kotlin/com/wafflestudio/csereal/core/about/api/AboutController.kt
  src/main/kotlin/com/wafflestudio/csereal/core/academics/api/AcademicsController.kt
  src/main/kotlin/com/wafflestudio/csereal/core/admissions/api/AdmissionsController.kt
  src/main/kotlin/com/wafflestudio/csereal/core/conference/api/ConferenceController.kt
  src/main/kotlin/com/wafflestudio/csereal/core/main/api/MainController.kt
  src/main/kotlin/com/wafflestudio/csereal/core/member/api/ProfessorController.kt
  src/main/kotlin/com/wafflestudio/csereal/core/member/api/StaffController.kt
  src/main/kotlin/com/wafflestudio/csereal/core/research/api/ResearchController.kt
Labels: Feat: API

#264 fix: adjust max thread and pool size
  src/main/resources/application.yaml
Labels: Fix

#265 Feat: 검색 refresh api 로컬에서 접근 가능하도록 변경
  caddy/Caddyfile
  src/main/kotlin/com/wafflestudio/csereal/core/main/api/MainController.kt
Labels: Feat: API, Config

#266 Config: 로그 파일 저장 추가, 항목 추가
  docker-compose-backend.yml
  src/main/resources/application.yaml
  src/main/resources/logback-spring.xml
Labels: CICD, Config

#273 Develop -> main merge
  src/main/kotlin/com/wafflestudio/csereal/core/academics/dto/DegreeRequirementsPageResponse.kt
  src/main/kotlin/com/wafflestudio/csereal/core/academics/service/AcademicsService.kt
  src/main/kotlin/com/wafflestudio/csereal/core/main/api/MainController.kt
Labels: Fix

#274 tcl 관련 수정
  src/main/kotlin/com/wafflestudio/csereal/core/conference/database/ConferenceEntity.kt
  src/main/kotlin/com/wafflestudio/csereal/core/conference/dto/ConferenceDto.kt
  src/main/kotlin/com/wafflestudio/csereal/core/conference/dto/ConferencePage.kt
  src/test/kotlin/com/wafflestudio/csereal/core/conference/service/ConferenceServiceTest.kt
Labels: Fix
