Repository wafflestudio/csereal-server, pull requests merged in 2024-05, with the labels that each got.

#278 TCL 코드, 인정IF 삭제 및 이름 순 정렬
  src/main/kotlin/com/wafflestudio/csereal/core/conference/database/ConferenceEntity.kt
  src/main/kotlin/com/wafflestudio/csereal/core/conference/database/ConferencePageEntity.kt
  src/main/kotlin/com/wafflestudio/csereal/core/conference/dto/ConferenceDto.kt
  src/main/kotlin/com/wafflestudio/csereal/core/conference/dto/ConferencePage.kt
  src/main/kotlin/com/wafflestudio/csereal/core/research/database/ResearchSearchEntity.kt
  src/test/kotlin/com/wafflestudio/csereal/core/conference/service/ConferenceServiceTest.kt
Labels: Fix

#279 feat: id list api for seo
  src/main/kotlin/com/wafflestudio/csereal/core/news/api/NewsController.kt
  src/main/kotlin/com/wafflestudio/csereal/core/news/database/NewsRepository.kt
  src/main/kotlin/com/wafflestudio/csereal/core/news/service/NewsService.kt
  src/main/kotlin/com/wafflestudio/csereal/core/notice/api/NoticeController.kt
  src/main/kotlin/com/wafflestudio/csereal/core/notice/database/NoticeRepository.kt
  src/main/kotlin/com/wafflestudio/csereal/core/notice/service/NoticeService.kt
  src/main/kotlin/com/wafflestudio/csereal/core/seminar/api/SeminarController.kt
  src/main/kotlin/com/wafflestudio/csereal/core/seminar/database/SeminarRepository.kt
  src/main/kotlin/com/wafflestudio/csereal/core/seminar/service/SeminarService.kt
Labels: Feat: API

#281 Feat: 새소식 생성 날짜가 아닌 실제 날짜 순으로 정렬되도록 변경
  src/main/kotlin/com/wafflestudio/csereal/core/news/database/NewsRepository.kt
Labels: Refactor, Feat: Logic
