Repository wafflestudio/csereal-server, pull requests merged in 2024-03, with the labels that each got.

#197 Refactor: Member Search
  src/main/kotlin/com/wafflestudio/csereal/core/about/api/AboutController.kt
  src/main/kotlin/com/wafflestudio/csereal/core/about/service/AboutService.kt
  src/main/kotlin/com/wafflestudio/csereal/core/admissions/service/AdmissionsService.kt
  src/main/kotlin/com/wafflestudio/csereal/core/member/api/MemberSearchController.kt
  src/main/kotlin/com/wafflestudio/csereal/core/member/api/res/MemberSearchResBody.kt
  src/main/kotlin/com/wafflestudio/csereal/core/member/api/res/MemberSearchResponseElement.kt
  src/main/kotlin/com/wafflestudio/csereal/core/member/database/MemberSearchEntity.kt
  src/main/kotlin/com/wafflestudio/csereal/core/member/database/MemberSearchRepository.kt
  src/main/kotlin/com/wafflestudio/csereal/core/member/dto/MemberSearchTopResponse.kt
  src/main/kotlin/com/wafflestudio/csereal/core/member/service/MemberSearchService.kt
  src/test/kotlin/com/wafflestudio/csereal/core/member/service/ProfessorServiceTest.kt
  src/test/kotlin/com/wafflestudio/csereal/core/member/service/StaffServiceTest.kt
Labels: Feat: API, Feat: Logic, Feat: DB

#199 feat: academics 패키지 이름에 맞게 변경
  src/main/kotlin/com/wafflestudio/csereal/core/academics/api/AcademicsController.kt
  src/main/kotlin/com/wafflestudio/csereal/core/academics/database/AcademicsEntity.kt
  src/main/kotlin/com/wafflestudio/csereal/core/academics/database/AcademicsPostType.kt
  src/main/kotlin/com/wafflestudio/csereal/core/academics/database/AcademicsRepository.kt
  src/main/kotlin/com/wafflestudio/csereal/core/academics/database/AcademicsSearchEntity.kt
  src/main/kotlin/com/wafflestudio/csereal/core/academics/dto/AcademicsDto.kt
  src/main/kotlin/com/wafflestudio/csereal/core/academics/dto/DegreeRequirementsDto.kt
  src/main/kotlin/com/wafflestudio/csereal/core/academics/dto/DegreeRequirementsPageResponse.kt
  src/main/kotlin/com/wafflestudio/csereal/core/academics/dto/GeneralStudiesPageResponse.kt
  src/main/kotlin/com/wafflestudio/csereal/core/academics/service/AcademicsService.kt
Labels: Feat: API, Feat: Logic

#200 Refactor: academics search
  src/main/kotlin/com/wafflestudio/csereal/core/academics/api/AcademicsController.kt
  src/main/kotlin/com/wafflestudio/csereal/core/academics/api/res/AcademicsSearchResBody.kt
  src/main/kotlin/com/wafflestudio/csereal/core/academics/api/res/AcademicsSearchResElement.kt
  src/main/kotlin/com/wafflestudio/csereal/core/academics/database/AcademicsSearchEntity.kt
  src/main/kotlin/com/wafflestudio/csereal/core/academics/database/AcademicsSearchRepository.kt
  src/main/kotlin/com/wafflestudio/csereal/core/academics/dto/AcademicsSearchPageResponse.kt
  src/main/kotlin/com/wafflestudio/csereal/core/academics/dto/AcademicsSearchResponseElement.kt
  src/main/kotlin/com/wafflestudio/csereal/core/academics/dto/AcademicsSearchTopResponse.kt
  src/main/kotlin/com/wafflestudio/csereal/core/academics/service/AcademicsSearchService.kt
Labels: Feat: API, Feat: Logic, Feat: DB

#201 Refactor: research search
  src/main/kotlin/com/wafflestudio/csereal/core/research/api/ResearchController.kt
  src/main/kotlin/com/wafflestudio/csereal/core/research/api/res/ResearchSearchResBody.kt
  src/main/kotlin/com/wafflestudio/csereal/core/research/api/res/ResearchSearchResElement.kt
  src/main/kotlin/com/wafflestudio/csereal/core/research/database/ResearchSearchEntity.kt
  src/main/kotlin/com/wafflestudio/csereal/core/research/database/ResearchSearchRepository.kt
  src/main/kotlin/com/wafflestudio/csereal/core/research/dto/ResearchSearchPageResponse.kt
  src/main/kotlin/com/wafflestudio/csereal/core/research/dto/ResearchSearchResponseElement.kt
  src/main/kotlin/com/wafflestudio/csereal/core/research/dto/ResearchSearchTopResponse.kt
  src/main/kotlin/com/wafflestudio/csereal/core/research/service/ResearchSearchService.kt
  src/test/kotlin/com/wafflestudio/csereal/core/reseach/service/ResearchServiceTest.kt
Labels: Feat: API, Feat: Logic, Feat: DB

#206 fix: 인증 로직 수정
  src/main/kotlin/com/wafflestudio/csereal/common/mockauth/DevAuthController.kt
  src/main/kotlin/com/wafflestudio/csereal/core/news/api/NewsController.kt
  src/main/kotlin/com/wafflestudio/csereal/core/notice/api/NoticeController.kt
  src/main/kotlin/com/wafflestudio/csereal/core/reservation/api/ReservationController.kt
  src/main/kotlin/com/wafflestudio/csereal/core/seminar/api/SeminarController.kt
  src/main/kotlin/com/wafflestudio/csereal/core/user/api/UserController.kt
Labels: Fix

#204 fix: migrateConferences에서 authenticatedStaff 삭제
  src/main/kotlin/com/wafflestudio/csereal/core/conference/api/ConferenceController.kt
Labels: Fix

#205 fix: simpleProfessorDto에서 status 추가
  src/main/kotlin/com/wafflestudio/csereal/core/member/dto/SimpleProfessorDto.kt
Labels: Fix

#209 fix: readDegreeRequirements에 파일 보이도록 추가
  src/main/kotlin/com/wafflestudio/csereal/core/academics/dto/DegreeRequirementsDto.kt
  src/main/kotlin/com/wafflestudio/csereal/core/academics/dto/DegreeRequirementsPageResponse.kt
  src/main/kotlin/com/wafflestudio/csereal/core/academics/service/AcademicsService.kt
Labels: Fix

#210 fix: StudentClubDto에 engName 추가
  src/main/kotlin/com/wafflestudio/csereal/core/about/api/AboutController.kt
  src/main/kotlin/com/wafflestudio/csereal/core/about/dto/StudentClubDto.kt
  src/main/kotlin/com/wafflestudio/csereal/core/about/service/AboutService.kt
Labels: Fix

#211 fix: researchEntity에 websiteURL 추가
  src/main/kotlin/com/wafflestudio/csereal/core/research/database/ResearchEntity.kt
  src/main/kotlin/com/wafflestudio/csereal/core/research/database/ResearchSearchEntity.kt
  src/main/kotlin/com/wafflestudio/csereal/core/research/dto/ResearchDto.kt
  src/test/kotlin/com/wafflestudio/csereal/core/member/service/ProfessorServiceTest.kt
  src/test/kotlin/com/wafflestudio/csereal/core/reseach/service/ResearchSearchServiceTest.kt
  src/test/kotlin/com/wafflestudio/csereal/core/reseach/service/ResearchServiceTest.kt
Labels: Fix

#213 Fix: `exchangepageNum`에서 total이 0일 경우 케이스 추가.
  src/main/kotlin/com/wafflestudio/csereal/common/utils/Utils.kt
  src/main/kotlin/com/wafflestudio/csereal/core/about/database/AboutRepository.kt
  src/main/kotlin/com/wafflestudio/csereal/core/academics/database/AcademicsSearchRepository.kt
  src/main/kotlin/com/wafflestudio/csereal/core/admissions/database/AdmissionsRepository.kt
  src/main/kotlin/com/wafflestudio/csereal/core/member/database/MemberSearchRepository.kt
  src/main/kotlin/com/wafflestudio/csereal/core/research/database/ResearchSearchRepository.kt
  src/test/kotlin/com/wafflestudio/csereal/common/util/UtilsTest.kt
Labels: Bug, Fix

#212 fix: readGeneralStudiesRequirements 추가
  src/main/kotlin/com/wafflestudio/csereal/core/academics/api/AcademicsController.kt
  src/main/kotlin/com/wafflestudio/csereal/core/academics/database/AcademicsPostType.kt
  src/main/kotlin/com/wafflestudio/csereal/core/academics/database/AcademicsRepository.kt
  src/main/kotlin/com/wafflestudio/csereal/core/academics/dto/DegreeRequirementsDto.kt
  src/main/kotlin/com/wafflestudio/csereal/core/academics/dto/GeneralStudiesDto.kt
  src/main/kotlin/com/wafflestudio/csereal/core/academics/dto/GeneralStudiesRequirementsPageResponse.kt
  src/main/kotlin/com/wafflestudio/csereal/core/academics/service/AcademicsService.kt
Labels: Fix

#216 Fix: Notice 비밀글 표시 안되도록 수정
  src/main/kotlin/com/wafflestudio/csereal/core/notice/api/NoticeController.kt
  src/main/kotlin/com/wafflestudio/csereal/core/notice/database/NoticeRepository.kt
  src/main/kotlin/com/wafflestudio/csereal/core/notice/service/NoticeService.kt
Labels: Fix, Feat: Logic

#218 Feat: Research 검색 결과 research 타입 상세화
  src/main/kotlin/com/wafflestudio/csereal/core/research/api/res/ResearchSearchResElement.kt
  src/main/kotlin/com/wafflestudio/csereal/core/research/database/ResearchPostType.kt
  src/main/kotlin/com/wafflestudio/csereal/core/research/database/ResearchSearchEntity.kt
  src/test/kotlin/com/wafflestudio/csereal/core/member/service/ProfessorServiceTest.kt
Labels: Refactor, Feat: API, Feat: Logic

#220 fix: pdf 타입 AttachmentResponse로 변경
  src/main/kotlin/com/wafflestudio/csereal/core/research/dto/LabDto.kt
  src/main/kotlin/com/wafflestudio/csereal/core/research/service/ResearchService.kt
  src/main/kotlin/com/wafflestudio/csereal/core/resource/attachment/service/AttachmentService.kt
Labels: Fix

#221 Feat: Academics 검색에 세부 타입 추가
  src/main/kotlin/com/wafflestudio/csereal/core/academics/api/res/AcademicsSearchResElement.kt
Labels: Refactor, Feat: API

#222 Fix: Admission 검색 결과 html 안나오게 제거
  src/main/kotlin/com/wafflestudio/csereal/core/admissions/api/res/AdmissionSearchResElem.kt
Labels: Feat: API, Feat: Logic

#217 fix: 단건 조회 & 통합 검색 권한 체크
  src/main/kotlin/com/wafflestudio/csereal/common/utils/Utils.kt
  src/main/kotlin/com/wafflestudio/csereal/core/news/api/NewsController.kt
  src/main/kotlin/com/wafflestudio/csereal/core/news/database/NewsRepository.kt
  src/main/kotlin/com/wafflestudio/csereal/core/news/service/NewsService.kt
  src/main/kotlin/com/wafflestudio/csereal/core/notice/api/NoticeController.kt
  src/main/kotlin/com/wafflestudio/csereal/core/notice/service/NoticeService.kt
  src/main/kotlin/com/wafflestudio/csereal/core/seminar/api/SeminarController.kt
  src/main/kotlin/com/wafflestudio/csereal/core/seminar/service/SeminarService.kt
Labels: Bug, Fix

#224 Fix: Academic 검색 결과에 student type 항상 추가
  src/main/kotlin/com/wafflestudio/csereal/core/academics/api/res/AcademicsSearchResElement.kt
Labels: Fix, Feat: API

#223 Config: Spring Boot 3.2, Java 21로 업그레이드, Virtual Thread 적용
  .github/workflows/build_and_test.yaml
  .github/workflows/deploy.yaml
  .github/workflows/ktlint-check.yml
  Dockerfile
  build.gradle.kts
  src/main/kotlin/com/wafflestudio/csereal/common/config/MySQLDialectCustom.kt
  src/main/resources/application.yaml
Labels: Refactor, CICD, Config

#226 Fix: 새소식 통합 검색 누락된 join condition 추가
  src/main/kotlin/com/wafflestudio/csereal/core/news/database/NewsRepository.kt
Labels: Fix

#228 Feat: Spring Boot 서버에서 Error 발생 시 Slack으로 로그 전송 기능 추가
  .github/workflows/deploy.yaml
  build.gradle.kts
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  src/main/kotlin/com/wafflestudio/csereal/common/config/CserealExceptionHandler.kt
  src/main/resources/application.yaml
  src/main/resources/logback-spring.xml
Labels: CICD, Config

#230 Hotfix: 누락된 Slack 정보 compose 파일에 추가.
  docker-compose-backend.yml
Labels: Hotfix, CICD, Config
