Repository wafflestudio/csereal-server, pull requests merged in 2025-04, with the labels that each got.

#355 Refactor/remove career entity
  src/main/kotlin/com/wafflestudio/csereal/core/member/database/CareerEntity.kt
  src/main/kotlin/com/wafflestudio/csereal/core/member/database/MemberSearchEntity.kt
  src/main/kotlin/com/wafflestudio/csereal/core/member/database/ProfessorEntity.kt
  src/main/kotlin/com/wafflestudio/csereal/core/member/database/ProfessorRepository.kt
  src/main/kotlin/com/wafflestudio/csereal/core/member/dto/ProfessorDto.kt
  src/main/kotlin/com/wafflestudio/csereal/core/member/service/ProfessorService.kt
  src/main/resources/db/migration/V7__update_professor.sql
  src/test/kotlin/com/wafflestudio/csereal/core/member/service/ProfessorServiceTest.kt
Labels: Feat: DB

#357 block LAB reservation if not staff
  src/main/kotlin/com/wafflestudio/csereal/core/reservation/service/ReservationService.kt
Labels: Fix

#363 Feat/combined search api
  build.gradle.kts
  src/main/kotlin/com/wafflestudio/csereal/core/main/api/v2/MainController.kt
  src/main/kotlin/com/wafflestudio/csereal/core/main/dto/TotalSearchResponse.kt
  src/main/kotlin/com/wafflestudio/csereal/core/main/service/MainService.kt
  src/test/kotlin/com/wafflestudio/csereal/core/main/service/TotalSearchTest.kt
Labels: Feat: API
