Repository wafflestudio/csereal-server, pull requests merged in 2025-03, with the labels that each got.

#346 feat: add authorization for modification apis of council file
  src/main/kotlin/com/wafflestudio/csereal/core/council/api/v2/CouncilController.kt
Labels: Feat: API

#347 feat: councilfile api 컨벤션 따르도록 수정
  src/main/kotlin/com/wafflestudio/csereal/core/council/api/req/CouncilFileModifyReq.kt
  src/main/kotlin/com/wafflestudio/csereal/core/council/api/v2/CouncilController.kt
Labels: Feat: API

#350 hotfix: findFirst
  src/main/kotlin/com/wafflestudio/csereal/core/reservation/database/ReservationRepository.kt
  src/main/kotlin/com/wafflestudio/csereal/core/reservation/service/ReservationService.kt
Labels: Hotfix

#351 fix: replace operators to space in mysql full text search
  src/main/kotlin/com/wafflestudio/csereal/common/repository/CommonRepository.kt
Labels: Bug, Feat: Logic, Feat: DB

#353 hotfix: modify denied url in caddyfile
  caddy/Caddyfile
Labels: Hotfix
